### ISSUE TITLE
デザイン、CSSの共通化

### ISSUE THREAD

**Issue by tomoki171923** [tomoki171923/nuancebook#108]
1.HOMEへ戻るボタンの設置
about
privacy
disclaimer
list
また、cssはcommonに配置

2.aタグのhoverや色の統合
また、cssはbaseに配置

**Comment by yukarri805** [comment]
3.footer修正

**Comment by yukarri805** [comment]
4.ディテイルの”類義語一覧”の文字を真ん中にする
テーブル”▶︎”微調整

**Comment by tomoki171923** [comment]
#119 
まーじ済み。
