### ISSUE TITLE
WordDetailのレイアウト替え

### ISSUE THREAD

**Issue by tomoki171923** [tomoki171923/nuancebook#146]
各単語の区切りを分かりやすくする

**Comment by yukarri805** [comment]
h1タグ、コンテンツ幅内に収める

**Comment by tomoki171923** [comment]
寺田さんの指摘も含めた画面遷移を一枚作る

**Comment by tomoki171923** [comment]
寺田さん打ち合わせメモ
以下で決定
・単語部分
web版；開きっぱなしでアコーディオン
スマホ版；閉じた状態でアコーディオン。リンクに開く。

・構成は以下。
①タイトル
②ページの説明
③目次（兼まとめ）
デザインイメージ
```
目次
ーーーー
①start 一般的な開始する
②begin ホゲホゲ
```
④各単語たち
h3を目立つようにして（帯などをつけて）、区切りをわかりやすくする。
```
start
/はつおん/　品詞
アウトライン
解説
＞オックスフォード
例文
```

⑤他ページのリンク
おすすめのページではなく、ページ一覧のリンクにする。

**Comment by tomoki171923** [comment]
アコーディオン参考
https://kodocode.net/design-css-acordion/
イメージはベースが上記の「枠線がないタイプのアコーディオン 」でボタン部分のイメージが「アコーディオンの開閉で親項目のデザインが〜」のやつ

**Comment by tomoki171923** [comment]
https://drive.google.com/drive/folders/1kQ6b_ly_5DQRoX0Pg_wAIj7dm5FB60TI
以下で画面遷移図作成済み
クローズ
