### ISSUE TITLE
コンテンツ修正　yukariから見た意見　

### ISSUE THREAD

**Issue by yukarri805** [tomoki171923/nuancebook#170]
- [x] **start** 
例文 シーズンは9月に開始する。
☞ 〜のシーズン(サッカーのシーズン)の方がわかりやすい

- [x] **alter**
解説文
例えば、“He changed his views.”（彼は意見を変えた）という文章からは、漠然と変更したという意味になりますが、“He changed his views”は、意見の一部を変更したという意味になります。
☞ 例文が一緒

- [x] **almost all**
名詞のpopulationを就職しているのでNGです。
☞ 就職×  修飾○  じゃないかな？

- [x] **nearly**
例文:デイビットはほとんど寝ていた。（実際はギリギリ寝ていない）
☞ どういう状況？？"ほとんど”は時間的な意味？”ギリギリ寝てない”だから寝そうで寝てないという意味？？
解説文に「近いけど到達してない」と書いてあるから、「目的地まで後少し」的な例文の方がいい気がする。。。

- [x] **bring・take**
解説:ものだけでなく人を連れて行く、いう意味もあります
☞ 人を連れて行くという意味もあります

- [x] **prevent**
例文:私は誰も中身を見られないようにした。
☞ 私は誰にも中身を見られないようにした。

- [x] **lend**
解説:銀行などの金融期間に限り
☞ 銀行などの金融機関に限り
解説:のように金利が発生することがあります。 
☞ もう少し文分かりやすくなるかな？
基本的には無料での貸し借りに使います。ですが、銀行などの金融機関に限り、「The bank lent me money at 3% interest. 銀行は3パーセントの利子でお金を私に貸した。」のように金利が発生する際にもlendを使用します。
とかどうかな？？

- [x] **occur**
「○The earthquake occurred here yesterday. 昨日ここで地震が起こった。」 
は正しいですが、 
「×Something occurred here yesterday. 昨日ここで何かが起こった。」 
☞ ○と×はカギカッコの外がいいな。

**Comment by tomoki171923** [comment]
> start
> 例文 シーズンは9月に開始する。
> ☞ 〜のシーズン(サッカーのシーズン)の方がわかりやすい
修正済み。

**Comment by tomoki171923** [comment]
>alter
>解説文
>例えば、“He changed his views.”（彼は意見を変えた）という文章からは、漠然と変更したという意味になりますが、“He changed his views”は、意見の一部を変更したという意味になります。
>☞ 例文が一緒

修正済み

**Comment by tomoki171923** [comment]
>almost all
>名詞のpopulationを就職しているのでNGです。
>☞ 就職× 修飾○ じゃないかな？

修正済み。

**Comment by tomoki171923** [comment]
>nearly
>例文:デイビットはほとんど寝ていた。（実際はギリギリ寝ていない）
>☞ どういう状況？？"ほとんど”は時間的な意味？”ギリギリ寝てない”だから寝そうで寝てないという意味？？
>解説文に「近いけど到達してない」と書いてあるから、「目的地まで後少し」的な例文の方がいい気がする。。。

GSSで修正済み。

**Comment by tomoki171923** [comment]
>occur
>「○The earthquake occurred here yesterday. 昨日ここで地震が起こった。」
>は正しいですが、
>「×Something occurred here yesterday. 昨日ここで何かが起こった。」
>☞ ○と×はカギカッコの外がいいな。

GSSで修正済。

**Comment by tomoki171923** [comment]
> lend
>解説:銀行などの金融期間に限り
>☞ 銀行などの金融機関に限り
>解説:のように金利が発生することがあります。
>☞ もう少し文分かりやすくなるかな？
>基本的には無料での貸し借りに使います。ですが、銀行などの金融機関に限り、「The bank lent me money at 3% interest. 銀行は3パーセントの利子でお金を私に貸した。」のように金利が発生する際にも>lendを使用します。
>とかどうかな？？

GSSで修正済。

**Comment by tomoki171923** [comment]
>bring・take
>解説:ものだけでなく人を連れて行く、いう意味もあります
>☞ 人を連れて行くという意味もあります

GSSで修正済。

**Comment by tomoki171923** [comment]
> prevent
>例文:私は誰も中身を見られないようにした。
>☞ 私は誰にも中身を見られないようにした。

GSSで修正済。

**Comment by tomoki171923** [comment]
本番機リリース済
