### ISSUE TITLE
WordDetailのレイアウト実装

### ISSUE THREAD

**Issue by tomoki171923** [tomoki171923/nuancebook#176]
画面遷移の作成後

**Comment by yukarri805** [comment]
アコーディオン参考
https://kodocode.net/design-css-acordion/
デザイン「枠線がないタイプのアコーディオン 」でボタン部分のイメージが「アコーディオンの開閉で親項目のデザインが〜」のやつ

**Comment by tomoki171923** [comment]
#207 
でマージ済み。残課題は別issueを切ったのでこちらはクローズ
