### ISSUE TITLE
寺田さん指摘　h1

### ISSUE THREAD

**Issue by tomoki171923** [tomoki171923/nuancebook#181]
フォントでシャドーをなくす。
バックの画像を暗めにしてh1のフォントをhomeのような感じに統一する

コンテンツ幅内に収める

**Comment by tomoki171923** [comment]
yukariメモ
[Webフォント20選](https://uxmilk.jp/52837)

**Comment by yukarri805** [comment]
#229 でデザインを変える

**Comment by tomoki171923** [comment]
残は
#229 
で対応する
 close
